### ISSUE TITLE
Spectator v4 API deprecated by riot

### ISSUE THREAD

**Issue by Shad9w** [MingweiSamuel/TeemoJS#20]
Riot has deprecated Spectator v4 on April 5th. Some other APIs appear to be down, but could not find any information if they have been deprecated or not. 

https://twitter.com/RiotGamesDevRel/status/1764780018025083163
https://developer.riotgames.com/api-status/

**Comment by MingweiSamuel** [comment]
Released 1.11.0 https://github.com/MingweiSamuel/TeemoJS/commit/ada598f207b51ec6b6803fa2851cc99668652a04
