### ISSUE TITLE
Tournament Stub

### ISSUE THREAD

**Issue by yodigi7** [MingweiSamuel/TeemoJS#7]
Add tournament stub endpoints

**Comment by MingweiSamuel** [comment]
Prerelease version supporting tournament endpoints: [2.0.0-alpha.2](https://www.npmjs.com/package/teemojs/v/2.0.0-alpha.2)

Example usage:
https://github.com/MingweiSamuel/TeemoJS/blob/2da0430/test/test.js#L138-L162

Calling syntax has changed, renamed `get` to `send` (`get` still works though):  
https://github.com/MingweiSamuel/TeemoJS#syntax  
https://github.com/MingweiSamuel/TeemoJS/blob/master/CHANGES_V2.md

Let me know if you have any suggestions on the calling syntax or anything else for v2. And of course if anything doesn't work

**Comment by MingweiSamuel** [comment]
Moving on to version 3 since version 2 got too messy and I didn't like it.
https://www.npmjs.com/package/teemojs/v/3.0.0-rc.1
